AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Lint/InterpolationCheck:
  Enabled: false
